### ISSUE TITLE
crates publishing team

### ISSUE THREAD

**Issue by michaelkirk** [georust/rust-world-file#3]
👋 Hi @frewsxcv, 

Following up on https://github.com/georust/meta/pull/21, I created a new [world-file-publishers team](https://github.com/orgs/georust/teams/world-file-publishers) for publishing to crates.io with you as a maintainer (actually since @frewsxcv is an organization owner, GH won't let me mark him as a maintainer, but it'd be redundant permissions anyway 🤷). 

Could you please [update the crate owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)? Specifically:

---

- [ ] update **world-file crate** owners on crates.io:

You are the only "user owners" of that crate, so only you can edit that crate's owners:

```
cd world-file
# I noticed this crate never had the georust/core team as an owner, so no need to remove them.
# 🔐 add small publishing group
cargo owner --add github:georust:world-file-publishers

# Consider adding another "user owner" so that if you become inaccessible someone could edit the owners
cargo owner --add <some user>

# make sure everything looks good 👀 
cargo owner --list
```
---

And if there's anyone else you'd like to be able to publish the crates, feel free to add them to your publishing team, or as a user-owner. Consider that user-owners, as opposed to owners-via-team, can themselves edit the crate's owners, which could be desirable, or not, depending.

Let me know if you have any questions, or you can review https://github.com/georust/meta/pull/21.

**Comment by frewsxcv** [comment]
done
